// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQzlJ_SDbY19Yp6-rjNO0NFFsH0K6Tws',
    appId: '1:366608576848:web:08a961c3d09524ebcdfc55',
    messagingSenderId: '366608576848',
    projectId: 'instant-maquillage',
    authDomain: 'instant-maquillage.firebaseapp.com',
    storageBucket: 'instant-maquillage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLbPNJJ5Qmmc4-6-zwX0s3N8ysadmCt0',
    appId: '1:366608576848:android:62bfa2c613b04761cdfc55',
    messagingSenderId: '366608576848',
    projectId: 'instant-maquillage',
    storageBucket: 'instant-maquillage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fIx3gBVX2tl6OX8R51vmJ9aRQu5XbEg',
    appId: '1:366608576848:ios:169fa6eacffa8521cdfc55',
    messagingSenderId: '366608576848',
    projectId: 'instant-maquillage',
    storageBucket: 'instant-maquillage.firebasestorage.app',
    androidClientId: '366608576848-1vup5t2uf6ae50m9eap4ier30bn5738e.apps.googleusercontent.com',
    iosClientId: '366608576848-1i0r6db2u5qu1o588ok3s8keam9ncijr.apps.googleusercontent.com',
    iosBundleId: 'com.company.instant.instantMaquillageBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9fIx3gBVX2tl6OX8R51vmJ9aRQu5XbEg',
    appId: '1:366608576848:ios:169fa6eacffa8521cdfc55',
    messagingSenderId: '366608576848',
    projectId: 'instant-maquillage',
    storageBucket: 'instant-maquillage.firebasestorage.app',
    androidClientId: '366608576848-1vup5t2uf6ae50m9eap4ier30bn5738e.apps.googleusercontent.com',
    iosClientId: '366608576848-1i0r6db2u5qu1o588ok3s8keam9ncijr.apps.googleusercontent.com',
    iosBundleId: 'com.company.instant.instantMaquillageBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQzlJ_SDbY19Yp6-rjNO0NFFsH0K6Tws',
    appId: '1:366608576848:web:199b2660b01606c0cdfc55',
    messagingSenderId: '366608576848',
    projectId: 'instant-maquillage',
    authDomain: 'instant-maquillage.firebaseapp.com',
    storageBucket: 'instant-maquillage.firebasestorage.app',
  );
}
